version: "3.8"

services:
  audio-trimmer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: audio-trimmer
    ports:
      - "8080:8080"
    volumes:
      - ./tmp:/app/tmp
    restart: unless-stopped

